version: '3.8'

services:
  manage-nginx:
    build: manager/docker/development/nginx
    volumes:
      - ./manager:/app
    depends_on:
      - manager-php-fpm
    ports:
      - "8080:80"
  manager-php-fpm:
    build: manager/docker/development/php-fpm
    environment:
      APP_DEBUG: 1
    volumes:
      - ./manager:/app
  manager-php-cli:
    build: manager/docker/development/php-cli
    environment:
      APP_DEBUG: 1
    volumes:
      - ./manager:/app
