services:
  manage-nginx:
    build: manager/docker/development/nginx
    volumes:
      - ./manager:/app
    depends_on:
      - manager-php-fpm
    ports:
      - "8080:80"
  manager-php-fpm:
    build: manager/docker/development/php-fpm
    volumes:
      - ./manager:/app
    depends_on:
      - manager-postgres
      - maildev
  manager-php-cli:
    build: manager/docker/development/php-cli
    volumes:
      - ./manager:/app
      - composer:/root/.composer/cache
    depends_on:
      - manager-postgres
      - maildev
  manager-postgres:
    image: postgres:16.4-alpine
    volumes:
      - manager-postgres:/var/lib/postgres/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"

volumes:
  manager-postgres:
  composer: